inpackage: False
with-expecter: True
testonly: False
# keeptree: True
exported: True
dir: "generated-files/mockery"
outpkg: "mockery"
filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go"
packages:
    {
        github.com/walteh/tftab/pkg/configuration:
            {
                interfaces:
                    {
                        Provider:
                            {
                                config:
                                    { mockname: "MockConfigurationProvider" },
                            },
                    },
            },
    }
# case: underscore
