{
    inpackage: false,
    with-expecter: true,
    testonly: false,
    exported: true,
    outpkg: mockery,
    filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go",
    packages:
        {
            github.com/walteh/tftab/pkg/configuration:
                {
                    interfaces:
                        {
                            Provider:
                                {
                                    config:
                                        {
                                            mockname: "MockConfigurationProvider",
                                        },
                                },
                        },
                },
        },
}
