jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 3
            - name: Run tests
              run: |
                  echo "Hello world"
name: test
"on":
    push:
        branches:
            - main
