{
    name: release,
    on: { push: { branches: [main] } },
    permissions: { contents: write, packages: write },
    env:
        {
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
            SH_FILE_INPUT_NAME: "tftab",
        },
    jobs:
        {
            auto-tag:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                name: Checkout code,
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                name: Bump version and push tag,
                                id: tag_version,
                                uses: anothrNick/github-tag-action@1.61.0,
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                        WITH_V: true,
                                        DEFAULT_BUMP: patch,
                                        DRY_RUN: true,
                                    },
                            },
                            {
                                name: Generate SHA256 and rename script,
                                id: prepare_script,
                                if: success(),
                                env:
                                    {
                                        SH_FILE_INPUT: "./${{ env.SH_FILE_INPUT_NAME }}.sh",
                                        SH_FILE_OUTPUT: "./${{ env.SH_FILE_INPUT_NAME }}-${{steps.tag_version.outputs.tag }}.sh",
                                    },
                                run: '
                                    echo "SH_FILE_OUTPUT=${{ env.SH_FILE_OUTPUT }}" >> $GITHUB_OUTPUT
                                    sha256=$(shasum -a 256 ${{ env.SH_FILE_INPUT }} | awk ''{ print $1 }'')
                                    mv ${{ env.SH_FILE_INPUT }} ${{ env.SH_FILE_OUTPUT }}
                                    sha256 > ${{ env.SH_FILE_OUTPUT }}.sha256',
                            },
                            {
                                name: Create GitHub Release,
                                if: success(),
                                uses: ncipollo/release-action@v1,
                                env:
                                    {
                                        SH_FILE_OUTPUT: "${{ steps.prepare_script.outputs.SH_FILE_OUTPUT }}}}",
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                    },
                                with:
                                    {
                                        artifacts: "${{ env.SH_FILE_OUTPUT }}\n${{ env.SH_FILE_OUTPUT }}.sha256",
                                        tag: "${{ steps.tag_version.outputs.tag }}",
                                        name: "${{ steps.tag_version.outputs.tag }}",
                                        body: "Auto-generated release for ${{ steps.tag_version.outputs.tag }}",
                                        draft: false,
                                        prerelease: false,
                                    },
                            },
                        ],
                },
        },
}
