{
    name: release,
    on: { push: { branches: [main] } },
    permissions: { contents: write, packages: write },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
    jobs:
        {
            main:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                name: Checkout code,
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                name: setup buildrc,
                                uses: walteh/actions/setup-buildrc@main,
                            },
                            { name: builrc open, run: "buildrc simple open" },
                            {
                                name: copy tftab,
                                run: "cp ./tftab.sh $BUILDRC_TARGZ && cp ./tftab.sh $BUILDRC_SHA256",
                            },
                            {
                                name: builrc upload,
                                run: "buildrc simple upload tftab",
                            },
                            { name: builrc close, run: "buildrc simple close" },
                        ],
                },
        },
}
