name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        uses: walteh/simver/.github/workflows/simver.yaml@7f0b639d508f4ab936b3a15df38a7ee95621a2da
        secrets: inherit
# Path: .github/workflows/simver.yaml
