name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        uses: walteh/simver/.github/workflows/simver.yaml@a49526e3841910a5cfc8982c2749164776c5f347
        secrets: inherit
# Path: .github/workflows/simver.yaml
