name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        uses: walteh/simver/.github/workflows/simver.yaml@2916c123009b22010e96a62575abb61c74752fe6
        secrets: inherit
# Path: .github/workflows/simver.yaml
