name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        runs-on: ubuntu-latest
        steps:
            - uses: walteh/simver@c8053658161670981e8bfce91c940ccf6d596dce
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
