name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        uses: walteh/simver/.github/workflows/simver.yaml@6b39641a9769c29bbe27fe91fd40cecc3758877b
        secrets: inherit
# Path: .github/workflows/simver.yaml
